[package]
name = "pubsub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
chrono = "0.4.31"
serde = { version = "1.0.195", features = ["derive"] }
timer = "0.2.0"
zmq = "0.10.0"
